/***********************************************************************/
/* Anyone is free to copy, modify, publish, use, compile, sell,        */
/* dismantle, dismember or distribute this software, either in source  */
/* code form or as object code or assembly code, for any purpose,      */
/* commercial or non-commercial, and by any means.                     */
/***********************************************************************/
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>

/***********************************************************************/
/* Write a program to check whether a given number is an ugly number.  */
/* Ugly numbers are positive numbers whose prime factors only          */
/* include 2, 3, 5. For example, 6, 8 are ugly while 14 is not ugly    */
/* since it includes another prime factor 7.                           */
/***********************************************************************/
bool isUgly(int num)
{
    int i;

    /* Return if the value is less than 0. */
    if (num < 0)
        return false;
    /* Keep dividing with 2, 3, and 5. The idea is that the multiples
    generated by non-prime values will eventually be divisible by 2, 3
    or 5. In the other case, the modulo check will fail and we will have a
    prime number. */
    for (i = 2; i < 6; ++i)
        while (!(num % i))
            num /= i;
    return num == 1 ? true : false;
}

/***********************************************************************/
/* main: Entry point!                                                  */
/*                                                                     */
/***********************************************************************/
int main()
{
    printf("Hello world!\n");
    return 0;
}
